name: CI构建
on:
  push:
    branches: [ main,master ]

env:
  APP_NAME: x-http # 给 APP 起一个名字

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@master

      - name: 同步代码
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /micro-server-code/$APP_NAME/ # 将代码发布到远程主机进行构建,当然你需要自己创建 /micro-server-code 目录 $APP_NAME 是全局的变量
          remote_host: ${{ secrets.Host }}
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.DeploySecret }} # 请使用 ssh-keygen -t rsa 生成秘钥对,然后将公钥拷贝到要操纵的目标器的/root/.ssh/authorized_keys里,再把私钥黏贴到 github 后台的secret里

      - name: 构建代码与发布
        uses: appleboy/ssh-action@master
        env: # 定义环境变量
          APP_NAME: ${{ env.APP_NAME }} # 避免下面的 script 使用主机上自带的环境变量
        with:
          host: ${{ secrets.Host }}
          username: root
          key: ${{ secrets.DeploySecret }}
          port: 22
          envs: APP_NAME  # 使用这个环境变量
          script: | # 下面的发布与重启,你可以使用 ansible 与 supervisor 配合进行,如果发布到本地,进行重启,你可以考虑用一下形式
            cd /micro-server-code/$APP_NAME
            pwd
            /usr/local/go/bin/go  build -o $APP_NAME
            cp -rf /micro-server-code/$APP_NAME/$APP_NAME /micro-server/$APP_NAME
            supervisorctl restart $APP_NAME

      - name: 构建结果通知
        uses: zzzze/webhook-trigger@master
        if: always() # 失败成功总会发送
        with:
          data: "{'event_type':'build-result','status':'${{ job.status }}',
          'repository':'${{ github.repository }}','job':'${{ github.job }}',
          'workflow':'${{ github.workflow }}'}"
          webhook_url: ${{ secrets.WebHookURL }}
          options: "-H \"Accept: application/vnd.github.everest-preview+json\" -H \"Authorization: token ${{ secrets.TOKEN }}\""





